import type { FixedOutputTemplateId } from "./fixedOutputTemplates";
import { FLEXIBLE_RENDER_REGIONS } from "./flexibleCatTemplate";
import {
  DEFAULT_FEATURE_REGION_PLAN,
  DEFAULT_FLEXIBLE_ANALYSIS,
  DEFAULT_MAIN_COLOR_ROLES,
  type FlexibleCatAnalysis,
  type FurColorRole,
  type FurRegionPlan,
} from "./flexibleCatTypes";

const templateCoatPreset: Record<
  FixedOutputTemplateId,
  FlexibleCatAnalysis["coatPreset"]
> = {
  cow_cat_dark: "dark_bicolor",
  white_cat: "solid_white",
  cow_cat_grey: "blue_white_bicolor",
  solid_blue: "solid_grey",
  cream_cat: "solid_white",
  blue_golden_shaded: "blue_golden_shaded",
  ragdoll_bicolor: "ragdoll_like_point",
  siamese_point: "colorpoint",
};

function makePlan(
  baseRole: FurColorRole,
  overrides: Partial<FurRegionPlan>,
): FurRegionPlan {
  return FLEXIBLE_RENDER_REGIONS.reduce<FurRegionPlan>((plan, region) => {
    plan[region] = overrides[region] ?? baseRole;
    return plan;
  }, {} as FurRegionPlan);
}

export const EDITABLE_FIXED_OUTPUT_PLANS: Record<
  FixedOutputTemplateId,
  FurRegionPlan
> = {
  white_cat: makePlan("white", {
    LEI: "pink",
    REI: "pink",
    MZ: "white",
    NZ: "white",
    CHIN: "white",
    LP: "white",
    RP: "white",
  }),

  cream_cat: makePlan("light_cream", {
    LEI: "pink",
    REI: "pink",
    FH: "cream",
    LFT: "cream",
    RFT: "cream",
    FCL: "light_cream",
    FCR: "light_cream",
    MZ: "white",
    NZ: "white",
    CHIN: "white",
    CH: "white",
    BU: "light_cream",
    BM: "light_cream",
    BE: "white",
    BD: "light_cream",
    LP: "cream",
    RP: "cream",
    TB: "cream",
    TM: "light_cream",
    TT: "light_cream",
  }),

  solid_blue: makePlan("blue_grey", {
    LEI: "pink",
    REI: "pink",
    LOF: "blue_grey",
    ROF: "blue_grey",
    LSH: "dark_blue_grey",
    RSH: "dark_blue_grey",
    LFL: "dark_blue_grey",
    RFL: "dark_blue_grey",
    LFM: "blue_grey",
    RFM: "blue_grey",
    LUL: "dark_blue_grey",
    RUL: "dark_blue_grey",
    LLL: "blue_grey",
    RLL: "blue_grey",
    TB: "dark_blue_grey",
    TM: "blue_grey",
    TT: "blue_grey",
  }),

  cow_cat_dark: makePlan("dark_grey", {
    LEI: "pink",
    REI: "pink",
    FCL: "white",
    FCR: "white",
    MZ: "white",
    NZ: "white",
    CHIN: "white",
    NU: "white",
    CH: "white",
    BU: "white",
    BM: "white",
    BE: "white",
    BD: "white",
    LBL: "dark_grey",
    RBL: "dark_grey",
    LP: "white",
    RP: "white",
    TT: "grey",
  }),

  cow_cat_grey: makePlan("white", {
    LEI: "pink",
    REI: "pink",
    LEO: "grey",
    REO: "grey",
    FH: "grey",
    LFT: "grey",
    RFT: "grey",
    LOF: "grey",
    ROF: "grey",
    LIF: "dark_grey",
    RIF: "dark_grey",
    LSH: "grey",
    RSH: "grey",
    LFL: "grey",
    RFL: "grey",
    LFM: "dark_grey",
    RFM: "dark_grey",
    LUA: "grey",
    RUA: "grey",
    LLA: "dark_grey",
    RLA: "dark_grey",
    LUL: "grey",
    RUL: "grey",
    TB: "dark_grey",
    TM: "grey",
    TT: "white",
  }),

  blue_golden_shaded: makePlan("light_cream", {
    LEI: "pink",
    REI: "pink",
    LEO: "golden",
    REO: "golden",
    FH: "taupe",
    LFT: "taupe",
    RFT: "taupe",
    LOF: "golden",
    ROF: "golden",
    LIF: "taupe",
    RIF: "taupe",
    FCL: "light_cream",
    FCR: "light_cream",
    MZ: "white",
    NZ: "white",
    CHIN: "white",
    NU: "white",
    CH: "white",
    BU: "light_cream",
    BM: "light_cream",
    BE: "white",
    BD: "light_cream",
    LSH: "golden",
    RSH: "golden",
    LFL: "golden",
    RFL: "golden",
    LFM: "light_cream",
    RFM: "light_cream",
    LBL: "light_cream",
    RBL: "light_cream",
    TB: "golden",
    TM: "golden",
    TT: "taupe",
  }),

  ragdoll_bicolor: makePlan("warm_white", {
    LEI: "pink",
    REI: "pink",
    LEO: "cream",
    REO: "cream",
    FH: "cream",
    LFT: "cream",
    RFT: "cream",
    LOF: "cream",
    ROF: "cream",
    LIF: "brown",
    RIF: "brown",
    LEA: "brown",
    REA: "brown",
    FCL: "white",
    FCR: "white",
    MZ: "white",
    NZ: "white",
    CHIN: "white",
    NU: "white",
    CH: "white",
    BE: "white",
    LSH: "cream",
    RSH: "cream",
    LFL: "cream",
    RFL: "cream",
    LBL: "cream",
    RBL: "cream",
    LP: "cream",
    RP: "cream",
    TB: "brown",
    TM: "brown",
    TT: "brown",
  }),

  siamese_point: makePlan("peach_cream", {
    LEI: "pink",
    REI: "pink",
    LEO: "brown",
    REO: "brown",
    FH: "peach_cream",
    LFT: "peach_cream",
    RFT: "peach_cream",
    LOF: "peach_cream",
    ROF: "peach_cream",
    LIF: "taupe",
    RIF: "taupe",
    FCL: "taupe",
    FCR: "taupe",
    LEA: "taupe",
    REA: "taupe",
    MZ: "dark_brown",
    NZ: "brown",
    CHIN: "peach_cream",
    NU: "peach_cream",
    CH: "peach_cream",
    BU: "peach_cream",
    BM: "peach_cream",
    BE: "peach_cream",
    BD: "peach_cream",
    LFL: "peach_cream",
    RFL: "peach_cream",
    LFM: "peach_cream",
    RFM: "peach_cream",
    LBL: "peach_cream",
    RBL: "peach_cream",
    LUA: "peach_cream",
    RUA: "peach_cream",
    LLA: "peach_cream",
    RLA: "peach_cream",
    LUL: "taupe",
    RUL: "taupe",
    LLL: "brown",
    RLL: "brown",
    LP: "brown",
    RP: "brown",
    TB: "taupe",
    TM: "brown",
    TT: "dark_brown",
  }),
};

export function createEditableAnalysisFromFixedOutput(
  templateId: FixedOutputTemplateId,
  imageHash = "matched",
): FlexibleCatAnalysis {
  return {
    ...DEFAULT_FLEXIBLE_ANALYSIS,
    analysisMode: "openai",
    imageHash,
    modeRecommendation: "fixed_template",
    coatPreset: templateCoatPreset[templateId],
    symmetry:
      templateId === "cow_cat_dark" || templateId === "cow_cat_grey"
        ? "mostly_symmetric"
        : "symmetric",
    mainColorRoles: DEFAULT_MAIN_COLOR_ROLES,
    furRegionPlan: EDITABLE_FIXED_OUTPUT_PLANS[templateId],
    featureRegionPlan: DEFAULT_FEATURE_REGION_PLAN,
    description: "Generated editable pixel cat color plan.",
    confidence: 1,
  };
}
